var gulp=require('gulp');//引包
var load=require('gulp-load-plugins')();
var browser=require('browser-sync').create();
gulp.task('sass',function(done){
	gulp.src('./src/css/*.scss')
	.pipe(load.sass())
	.pipe(load.minifyCss())
	.pipe(gulp.dest('./dist/css/'))
	done()
})
gulp.task('img',function(done){
	gulp.src('./src/img/**')
	.pipe(gulp.dest('./dist/img/'))
	done()
})
gulp.task('css',function(done){
	gulp.src('./src/css/*.css')
	.pipe(load.minifyCss())
	.pipe(gulp.dest('./dist/css/'))
	done()
})
gulp.task('js',function(done){
	gulp.src('./src/js/*.js')
	.pipe(gulp.dest('./dist/js/'))
	done()
})
gulp.task('json',function(done){
	gulp.src('./src/js/*.json')
	.pipe(gulp.dest('./dist/js/'))
	done()
})
gulp.task('html',function(done){
	gulp.src('./src/*.html')
	.pipe(load.minifyHtml())
	.pipe(gulp.dest('./dist/'))
	done()
})
gulp.task('server',gulp.series(gulp.parallel('html','sass'),function(done){
	browser.init({
		server:'./dist/',
		port:80
	})
	gulp.watch('./src/',gulp.series(gulp.parallel('html','sass'),function(done){
		browser.reload()
		done()
	}))
	done()
}))